### ISSUE TITLE
What is the license of this work?

### ISSUE THREAD

**Issue by datajms** [weinajin/end-user-xai#1]
Hello EUCA team,

Huge work with real-life studies, templates, structured analyses, etc. Congrats!

However, I have not found any mention of a license for this content. Maybe I just missed it.
From the way it is presented, I assume that it looks like a Creative Commons licence, but would you mind clarifying that aspect?

It would help me a lot on knowing how and what I can use, among the templates you provides, etc.

Best,

**Comment by weinajin** [comment]
Hi datajms,  
Thanks for your message! I've added the cc license to the work. Feel free to provide any comments or feedback:)

**Comment by datajms** [comment]
@weinajin, Great, thanks for clarifying!
I may use some part of it, or ideas in future project. I'll try to give feedbacks then!
